
# Site settings
email: kontakt@artinventis.pl
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://artinventis.pl" # the base hostname & protocol for your site
languages: ["pl", "en"]
exclude_from_localizations: ["javascript", "images", "css"]


# Build settings
markdown: kramdown

# highlighter: true
# auto: true

gems:
  - jekyll-multiple-languages-plugin
